<?php

/**
 * @file
 * Contains page_json.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function page_json_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the page_json module.
    case 'help.page.page_json':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module generates json of the node having "page" content type.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter() on behalf of page_json.module.
 */
function page_json_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'system_site_information_settings') {
    $config = \Drupal::service('config.factory')->getEditable('system.site');
    $siteapikey = $config->get('siteapikey');

    $form['api_config'] = [
      '#type' => 'fieldset',
      '#title' => t('API Configuration'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    ];

    // Textbox for API secret key.
    $form['api_config']['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => $siteapikey,
      '#description' => t('Enter your API secret key here.'),
      '#required' => FALSE,
      '#attributes' => [
        'placeholder' => t('No API Key yet'),
      ],
    ];

    $form['actions']['submit']['#submit'][] = '_custom_settings_submit_handler';

  }
}

/**
 * Custom Submit Handler .
 */
function _custom_settings_submit_handler(array $form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $siteapikey = $form_state->getValue('siteapikey');
  $config->set('siteapikey', $siteapikey);
  $config->save();
  \Drupal::messenger()->addMessage('Site API Key has been saved with the value- ' . $siteapikey);

}
